version: "{build}"

environment:
  matrix:
    - nodejs_version: 5.1.0

install:
  - ps: $env:package_version = (Get-Content -Raw -Path .nvmrc)
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm update

build: off

test_script:
  - node --version && npm --version
  - npm test

cache:
  - node_modules            # local npm modules

matrix:
  fast_finish: true
