version: "{build}"

environment:
  matrix:
    - nodejs_version: 5.1.0

install:
  - ps: $env:package_version = (Get-Content -Raw -Path package.json | ConvertFrom-Json)
  - ps: Update-AppveyorBuild -Version "$env:package_version-$env:APPVEYOR_BUILD_NUMBER"
  - npm install
  - npm update

build: off

test_script:
  - node --version && npm --version
  - npm test

cache:
  - node_modules            # local npm modules

matrix:
  fast_finish: true
