language: node_js
branches:
  only:
  - master
before_install:
  - sudo apt-get install libpng16-dev
after_success:
  - npm run release
  - git push --follow-tags https://$GH_TOKEN@github.com/$TRAVIS_REPO_SLUG HEAD:$TRAVIS_BRANCH
env:
  global:
    secure: O6MZLL2iFyBn85t9IFA4FPFujf3xEn4B5CJAP4aUGpDTXHrvG+5Eyj2kU7carBN38uVgb3VDJ/SoWybHfo7o+wy0jIEPEct/xmfb1vzckbLaR+62OlrLDoqTs/jlNLVeQWo46WwYdAVUIdwaCoboi98S7sdbrOs/sWmVKnNtmnlLRuT6hamZMS43KLSpZfq7n913jEZrkHFGxILki/yrnd14+0bTTy2d1PQYMawy2lj+PdmNGX+to+QBTeTtaY0WCc4INXZQt2ckNy5NMeP8UgagITwRj1sJpAv41lCuhRIQ+ZvuverfvO+ZQQ6K6TaeC2VnnlYs09fi4GOTzzJmNZe+2kWBCywy+OIle7jIjFH5hxmds1Li88MCaplBlRi7eh8rQtxrmvWT+4U/kZ7eZFHf/tdi2rGD5lSpGVEJeHf4oWdunaVlv8P7T1uWxFIDIxL6MtlJiYeINO2+9anR369kWUsr2hNmuNzY77AZrPTD+wyfZg9v+2QFclwUlW0vGKwXDlJqqH6cUx2bSZ6uByRdpUMpApoJsV2GbBM0R9Yn+jNgupNZLC5cjeClcuRORB4gy+PTUFWUUaHH4CXbxYj0GoduI9+AZPu3LfLhUOiC5VpOKeXlOWW9IGV3o6vf8Zw8nPNmLk/VFqyOY4QxtKRHbD6twAu/qMOzEKYh2Pc=
addons:
  sauce_connect:
    username: gerbeth
  jwt:
    secure: MuvSFUyXMCooM5sITZ7uCts6R3E0Z72UnOmap/VvY7j+UOexa7exx3YdH08xscDcZ0GzHhGgZ9mW2JcyOpsOac5dEYxKrcZkrNpLRYPQdAYG0VKxCm5Zij/qO0aOZPRK5H4+DoCr1dXqfM0fFMLMG3JymZvA9yZPZGorLpRlwyyTa4bJK3qcitsRFmsuloLwMMzbEzh8CzLSflbviP2wzPQG/eF5ltI2XYMLK2+4fWCSh0l5Q5G9B/uVWWwtL/g0kmqWBdUc7jyAse43lZtM31EVh+UugmGxGnX6W8yeOGOGBnALifq2vOjpAS2qR8ZcWV6LD7vS5ikhXs9zqR/HRn6JECg+dJgrDZg2/ngFoXn9OTEDq0oK8tpchkMKu1syvQ4SxGRtI71Du07tfibpE/A0FdGZBBJsAlIS2Nc+BYyRwiSEaxASLDNmhH2g4V3siITfiygX0916kEQqHuEnK3AXn8JQwZpVsusylFkEwIeg9iaOiJLAnu+qfd7LJ66L6PVhNWddz7RNhw3Z6UNE66YBd5swlbnSnnGUM45wtSaxITTav8noqVv/P0Yna50l83DPUhwA/E1R+pCgVTbjPrj9bh+eK/V/XCX56KQPnDZ1rb14OYjheU3wA0s9+dHPBiLtiuTPQLtghfORhdEfxi4dl+tI0o2rcqJGIsdKN5U=
