language: node_js
before_install:
  - echo -e "machine github.com\n  login $GITHUB_TOKEN" >> ~/.netrc
after_success:
  - npm run release
  - git commit -m "[ci skip] travis update"
  - git push origin HEAD:master --follow-tags
