language: node_js
before_install:
  - echo -e "machine github.com\n  login $GITHUB_TOKEN" >> ~/.netrc
  - npm install -g ci-skipper
after_success:
  - ci-skipper on
  - npm run release
  - export MSG=$(git log -1 --pretty=%B)
  - echo $MSG
  - git commit --amend -m "$MSG [ci skip]"
  - git push --follow-tags
