language: node_js
before_install:
  - echo -e "machine github.com\n  login $GITHUB_TOKEN" >> ~/.netrc
before_deploy:
  - npm run release
deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: *
  skip_cleanup: true
  on:
    tags: true
