language: node_js
before_install:
  - echo -e "machine github.com\n  login $GITHUB_TOKEN" >> ~/.netrc
  - npm install -g ci-skipper
after_success:
  - ci-skipper on
  - npm run release
  - export message = "$(git log -1)"
  - echo $message
  - git push origin HEAD:master
  - git push --tags
